# Generated by Django 6.0.4 on 2026-04-20 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('page1', models.ImageField(blank=True, null=True, upload_to='zines/pages/')),
                ('page2', models.ImageField(blank=True, null=True, upload_to='zines/pages/')),
                ('page3', models.ImageField(blank=True, null=True, upload_to='zines/pages/')),
                ('page4', models.ImageField(blank=True, null=True, upload_to='zines/pages/')),
                ('page5', models.ImageField(blank=True, null=True, upload_to='zines/pages/')),
                ('page6', models.ImageField(blank=True, null=True, upload_to='zines/pages/')),
                ('page_back', models.ImageField(blank=True, null=True, upload_to='zines/pages/')),
                ('page_cover', models.ImageField(blank=True, null=True, upload_to='zines/pages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
